// ittesa-frontend/src/app/layouts/main-layout/main-layout.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { SidebarComponent } from '../../components/sidebar/sidebar.component';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-main-layout',
  standalone: true,
  imports: [CommonModule, RouterOutlet, SidebarComponent],
  template: `
    <div class="flex">
      <app-sidebar></app-sidebar>
      <div class="main-content">
        <header class="header">
          <div>
            <h2 class="text-lg font-semibold text-gray-800">ITESSA Dashboard</h2>
          </div>
          <div class="flex items-center gap-4">
            <span class="text-sm text-gray-600">{{ currentUser?.fullName }}</span>
            <div class="w-10 h-10 rounded-full bg-primary-600 flex items-center justify-center text-white font-medium">
              {{ getUserInitials() }}
            </div>
          </div>
        </header>
        <div class="p-6">
          <router-outlet></router-outlet>
        </div>
      </div>
    </div>
  `
})
export class MainLayoutComponent {
  currentUser: any = null;

  constructor(private authService: AuthService) {
    this.currentUser = this.authService.getCurrentUser();
  }

  getUserInitials(): string {
    if (!this.currentUser?.fullName) return 'U';
    return this.currentUser.fullName
      .split(' ')
      .map((n: string) => n[0])
      .join('')
      .toUpperCase()
      .substring(0, 2);
  }
}

// ittesa-frontend/src/layouts/MainLayout.tsx
import { Outlet } from 'react-router-dom';
import { Sidebar } from '@/components/Sidebar';
import { useAuthStore } from '@/stores/authStore';
import { User } from 'lucide-react';

export function MainLayout() {
  const { user } = useAuthStore();

  return (
    <div className="flex h-screen bg-gray-50">
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden">
        <header className="h-16 bg-white border-b border-gray-200 flex items-center justify-between px-6">
          <h2 className="text-lg font-semibold text-gray-800">
            IT Employee Self Service Application
          </h2>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-primary-500 rounded-full flex items-center justify-center">
              <User size={18} className="text-white" />
            </div>
            <div className="text-sm">
              <p className="font-medium text-gray-800">{user?.fullName || 'User'}</p>
              <p className="text-gray-500">{user?.role?.name || 'User'}</p>
            </div>
          </div>
        </header>
        <main className="flex-1 overflow-y-auto p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}
